/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Actions;
import controllers.Controller;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import models.entity.BandColor;
import util.GlobalConstants;

/**
 *
 * @author Invitado
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     *
     * @param controller
     */
    public MainWindow(Controller controller) {
        initComponents();
        drawingBoard = new DrawingBoard(resistanceInfoPanel);
        System.out.println("Container size is " + resistanceInfoPanel.getSize());
        resistanceInfoPanel.setLayout(new BorderLayout());
        resistanceInfoPanel.add(drawingBoard, BorderLayout.CENTER);
        addComponentsActionListener(controller);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resistanceSettingsPanel = new javax.swing.JPanel();
        bandsAmountPanel = new javax.swing.JPanel();
        bandAmountJCB = new javax.swing.JComboBox<>();
        bandsValuesPanel = new javax.swing.JPanel();
        bandOneJCB = new javax.swing.JComboBox<>();
        bandTwoJCB = new javax.swing.JComboBox<>();
        bandThreeJCB = new javax.swing.JComboBox<>();
        multiplicatorJCB = new javax.swing.JComboBox<>();
        tolerance = new javax.swing.JComboBox<>();
        ppmJCB = new javax.swing.JComboBox<>();
        startButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        resistanceInfoPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        theoricalValueJTF = new javax.swing.JTextField();
        PPMJTF = new javax.swing.JTextField();
        minValueJTF = new javax.swing.JTextField();
        maxValueJTF = new javax.swing.JTextField();
        tolerancePercentageJTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resistance Simulator");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        resistanceSettingsPanel.setBackground(new java.awt.Color(255, 255, 255));

        bandsAmountPanel.setBackground(new java.awt.Color(255, 255, 255));
        bandsAmountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bands amount", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        bandAmountJCB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bandAmountJCB.setModel(new javax.swing.DefaultComboBoxModel<>(new Byte[] { 4, 5, 6 }));
        bandAmountJCB.addItemListener(new ItemChangeListener());

        javax.swing.GroupLayout bandsAmountPanelLayout = new javax.swing.GroupLayout(bandsAmountPanel);
        bandsAmountPanel.setLayout(bandsAmountPanelLayout);
        bandsAmountPanelLayout.setHorizontalGroup(
            bandsAmountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsAmountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bandAmountJCB, 0, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        bandsAmountPanelLayout.setVerticalGroup(
            bandsAmountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsAmountPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bandAmountJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bandsValuesPanel.setBackground(new java.awt.Color(255, 255, 255));
        bandsValuesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bands' values", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        bandOneJCB.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bandOneJCB.setModel(new javax.swing.DefaultComboBoxModel<>(BandColor.values()));

        bandTwoJCB.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bandTwoJCB.setModel(new javax.swing.DefaultComboBoxModel<>(BandColor.values()));

        bandThreeJCB.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bandThreeJCB.setModel(new javax.swing.DefaultComboBoxModel<>(BandColor.values()));

        multiplicatorJCB.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        multiplicatorJCB.setModel(new DefaultComboBoxModel((((byte)bandAmountJCB.getSelectedItem())==4)? GlobalConstants.FOUR_BAND_MULTIPLICATOR:GlobalConstants.FIVE_OR_SIX_BAND_MULTIPLICATOR));

        tolerance.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tolerance.setModel(new javax.swing.DefaultComboBoxModel<>(GlobalConstants.TOLERANCE_BANDCOLOR));

        ppmJCB.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ppmJCB.setModel(new javax.swing.DefaultComboBoxModel<>(GlobalConstants.PPM_BANDCOLOR));

        javax.swing.GroupLayout bandsValuesPanelLayout = new javax.swing.GroupLayout(bandsValuesPanel);
        bandsValuesPanel.setLayout(bandsValuesPanelLayout);
        bandsValuesPanelLayout.setHorizontalGroup(
            bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsValuesPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bandOneJCB, 0, 69, Short.MAX_VALUE)
                    .addComponent(multiplicatorJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bandTwoJCB, 0, 69, Short.MAX_VALUE)
                    .addComponent(tolerance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bandThreeJCB, 0, 66, Short.MAX_VALUE)
                    .addComponent(ppmJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        bandsValuesPanelLayout.setVerticalGroup(
            bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandsValuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandOneJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandTwoJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandThreeJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(bandsValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicatorJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tolerance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppmJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        startButton.setBackground(new java.awt.Color(153, 153, 255));
        startButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Try");

        javax.swing.GroupLayout resistanceSettingsPanelLayout = new javax.swing.GroupLayout(resistanceSettingsPanel);
        resistanceSettingsPanel.setLayout(resistanceSettingsPanelLayout);
        resistanceSettingsPanelLayout.setHorizontalGroup(
            resistanceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resistanceSettingsPanelLayout.createSequentialGroup()
                .addComponent(bandsAmountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bandsValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(24, 24, 24))
        );
        resistanceSettingsPanelLayout.setVerticalGroup(
            resistanceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resistanceSettingsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(resistanceSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bandsValuesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bandsAmountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(resistanceSettingsPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resistanceInfoPanel.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout resistanceInfoPanelLayout = new javax.swing.GroupLayout(resistanceInfoPanel);
        resistanceInfoPanel.setLayout(resistanceInfoPanelLayout);
        resistanceInfoPanelLayout.setHorizontalGroup(
            resistanceInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        resistanceInfoPanelLayout.setVerticalGroup(
            resistanceInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        theoricalValueJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Theorical Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        PPMJTF.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        PPMJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PPM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        minValueJTF.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        minValueJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Minium Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        maxValueJTF.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        maxValueJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maxium Value", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        tolerancePercentageJTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tolerancePercentageJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tolerance (%)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(theoricalValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(minValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maxValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(tolerancePercentageJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(PPMJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theoricalValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxValueJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tolerancePercentageJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPMJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resistanceInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resistanceSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(resistanceSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resistanceInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PPMJTF;
    private javax.swing.JComboBox<Byte> bandAmountJCB;
    private javax.swing.JComboBox<BandColor> bandOneJCB;
    private javax.swing.JComboBox<BandColor> bandThreeJCB;
    private javax.swing.JComboBox<BandColor> bandTwoJCB;
    private javax.swing.JPanel bandsAmountPanel;
    private javax.swing.JPanel bandsValuesPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField maxValueJTF;
    private javax.swing.JTextField minValueJTF;
    private javax.swing.JComboBox<BandColor> multiplicatorJCB;
    private javax.swing.JComboBox<BandColor> ppmJCB;
    private javax.swing.JPanel resistanceInfoPanel;
    private javax.swing.JPanel resistanceSettingsPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField theoricalValueJTF;
    private javax.swing.JComboBox<BandColor> tolerance;
    private javax.swing.JTextField tolerancePercentageJTF;
    // End of variables declaration//GEN-END:variables

    private DrawingBoard drawingBoard;

    private void addComponentsActionListener(Controller controller) {
        startButton.addActionListener(controller);
        startButton.setActionCommand(Actions.CALCULATE_RESISTANCE.name());
    }

    public BandColor[] getBandColors() {
        byte bandAmount = (byte) bandAmountJCB.getSelectedItem();
        System.out.println("Es de "+bandAmount+" bandas");
        if (bandAmount == 4) {
            return new BandColor[]{(BandColor) bandOneJCB.getSelectedItem(), (BandColor) bandTwoJCB.getSelectedItem(), (BandColor) multiplicatorJCB.getSelectedItem(), (BandColor) tolerance.getSelectedItem()};
        } else if (bandAmount == 5) {
            return new BandColor[]{(BandColor) bandOneJCB.getSelectedItem(), (BandColor) bandTwoJCB.getSelectedItem(), (BandColor) bandThreeJCB.getSelectedItem(), (BandColor) multiplicatorJCB.getSelectedItem(), (BandColor) tolerance.getSelectedItem()};
        } else {
            return new BandColor[]{(BandColor) bandOneJCB.getSelectedItem(), (BandColor) bandTwoJCB.getSelectedItem(), (BandColor) bandThreeJCB.getSelectedItem(), (BandColor) multiplicatorJCB.getSelectedItem(), (BandColor) tolerance.getSelectedItem(), (BandColor) ppmJCB.getSelectedItem()};
        }
    }

    public void showResistanceValues(Object[] resistanceValues, BandColor[] bandColors) {
        theoricalValueJTF.setText("" + resistanceValues[0]);
        minValueJTF.setText("" + resistanceValues[1]);
        maxValueJTF.setText("" + resistanceValues[2]);
        tolerancePercentageJTF.setText("" + resistanceValues[3]);
        PPMJTF.setText("" + resistanceValues[4]);
        drawingBoard.drawResistance(bandColors);
    }

    private class ItemChangeListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                switch (Integer.parseInt(event.getItem().toString())) {
                    case 4:
                        multiplicatorJCB.setModel(new DefaultComboBoxModel<>(GlobalConstants.FOUR_BAND_MULTIPLICATOR));
                        if (bandThreeJCB.isEnabled()) {
                            bandThreeJCB.setEnabled(false);
                        }
                        if (ppmJCB.isEnabled()) {
                            ppmJCB.setEnabled(false);
                        }
                        break;
                    case 5:
                        multiplicatorJCB.setModel(new DefaultComboBoxModel<>(GlobalConstants.FIVE_OR_SIX_BAND_MULTIPLICATOR));
                        if (!bandThreeJCB.isEnabled()) {
                            bandThreeJCB.setEnabled(true);
                        }
                        if (ppmJCB.isEnabled()) {
                            ppmJCB.setEnabled(false);
                        }
                        break;
                    case 6:
                        multiplicatorJCB.setModel(new DefaultComboBoxModel<>(GlobalConstants.FIVE_OR_SIX_BAND_MULTIPLICATOR));
                        if (!bandThreeJCB.isEnabled()) {
                            bandThreeJCB.setEnabled(true);
                        }
                        if (!ppmJCB.isEnabled()) {
                            ppmJCB.setEnabled(true);
                        }
                        break;
                }
            }
        }
    }
}
